books/urls.py
from django.conf.urls import url
from books import views


urlpatterns = [
    url(r'^index/', views.index, name='index'), # 主页路由
]

bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books')), # 书籍app路由
    url(r'^users/', include('users.urls', namespace='users')), # 用户app路由
]

users/urls.py
from django.conf.urls import url
from users import views


urlpatterns = [
    url(r'^register/', views.register, name='register'), # 注册路由
    url(r'^register_handle/', views.register_handle, name='register_handle'), # 注册处理路由
    url(r'^login/', views.login, name='login'), # 登录路由
    url(r'^login_handle/', views.login_handle, name='login_handle'), # 登陆处理路由
]

books/models.py
# coding: utf-8

from django.db import models
from db.BaseModels import BaseModel

users/models.py
# coding; utf-8
from hashlib import sha1
from django.db import models
from db.BaseModels import BaseModel

# Create your models here.

# 定义一个对密码加密的hash函数
def get_hash(str):
    '''取一个字符串的hash值'''
    sh = sha1()
    sh.update(str.encode('utf-8'))

    return sh.hexdigest()


# 用户管理器 ：添加和查找功能
class UsersManager(models.Manager):

    def add_one_user(self, username, password, email):
        '''添加一个账户'''
        user = self.create(username=username,
                           password=get_hash(password),
                           email=email)

        return user
    def get_user(self, username, password):
        '''根据用户密码查询'''
        try:
            user_message = self.get(username=username, password=get_hash(password))

        except self.model.DoesNotExist:
            user_message = None

        return user_message


    def get_user_username(self, username):
        '''根据用户名查找账户信息'''
        try:
            user = self.get(username=username)

        except self.model.DoesNotExist:
            # 账户不存在
            user = None

        return user

    def get_user_password(self, password):
        '''密码验证'''
        try:
            password = self.get(password=get_hash(password))

        except self.model.DoesNotExist:
            # 密码不存在
            password = None

        return password


# 设计用户表
class UserSheet(BaseModel):
    '''用户模型类'''
    username = models.CharField(max_length=20, verbose_name='用户名')
    password = models.CharField(max_length=40, verbose_name='密码')
    email = models.EmailField(verbose_name='邮箱')
    is_active = models.BooleanField(default=False ,verbose_name='激活状态')

    # 用户表管理器
    objects = UsersManager()

    class Meta:
        # 数据库表名
        db_table = 's_user_message'

books/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'books/index.html')

users/views.py
# coding: utf-8

import re
from users.models import UserSheet
from django.http import JsonResponse
from utils.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse


# Create your views here.
# 注册页面
@csrf_exempt
def register(request):
    return render(request, 'users/register.html')


# 注册处理页面
@csrf_exempt
def register_handle(request):
    # 1.获取数据
    username = request.POST.get('name')
    password = request.POST.get('password')
    cwpd = request.POST.get('cwpd')
    email = request.POST.get('email')

    # 验证用户名在数据库中是否存在！！
    is_exist = UserSheet.objects.filter(username=username)
    # 如果存在则提示用户已存在
    if is_exist:
        return JsonResponse({'code': 1})

    # 验证两次密码是否一样
    if password != cwpd:
        return JsonResponse({'code': 2})

    # 进行数据校验
    if not all([username, password, email]):
        # 有数据为空
        return JsonResponse({'code': 3})

    # 邮箱验证
    if not re.match(r'^[a-z0-9][\w\\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', str(email)):
        # 邮箱不合法
        return JsonResponse({'code': 4})

    # 进行业务处理：注册，向用户系统中添加账户
    passport = UserSheet.objects.add_one_user(username=username,
                                              password=password,
                                              email=email)
    passport.objects.save()

    # 注册完毕！
    next_url = request.session.get('url_path', reverse('users:login'))
    return JsonResponse({'code': 5, 'next_url': next_url})


# 登录页面
def login(request):
    return render(request, 'users/login.html')


# 登录处理页面
def login_handle(request):
    pass

templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {% block title %}
	<title>尚硅谷书城</title>
    {% endblock title %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
{% block head %}
    <div class="header_con">
            <div class="header">
                {% block head_cont %}
                <div class="welcome fl">欢迎您来到尚硅谷书城!</div>
                {% endblock head_cont %}
                <div class="fr">
                    <div class="login_btn fl">
                        <span>|</span>
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
                        <span>|</span>
                        <a href="#">个人主页</a>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">注销</a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock head %}
    {% block content %}
    {% endblock content %}

{% block buttom %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock buttom %}
</body>
</html>

templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h1>hello world!!</h1>
</body>
</html>

templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
<title>尚硅谷书城登陆页面</title>
{% endblock title %}
{% block content %}
{% block head %}
{% endblock head %}
	<div class="login_top clearfix">
		<a href="#" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学计算机 · 来尚硅谷</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    <input type="text"  id="username" class="name_input" value="" placeholder="请输入用户名">
                        <div class="user_error">用户名输入正确！</div>
                    <input type="password"  id="password" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox"  id="remember" checked >
                        <div class="user_error">用户名输入正确！</div>
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <button id="btnLogin" type="button" value="" class="input_submit">登 录</button>

				</div>
			</div>
		</div>
	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
{#            设置监听输入的username#}
            $('#password').click(function () {
                 var username = $('#username').val();
                $.post('{% url 'users:login_handle' %}', {'username':username}, function(data){
                        if (data.code === 0){
                            $('#username').next().show()
                        }else if (data.code === 1){
                            $('#username').next().html('用户名不存在').show()
                        }
                });
            });

            $('button').click(function () {

                var username = $('#username').val();
                var password = $('#password').val();
                var remember = $('#remember').val();
                var params = {
                    'username':username,
                    'password': password,
                    'remember': remember
                };

                $.post('{% url 'users:login_handle' %}', params, function(data){

                        if (data.code === 3){
                            $('#password').next().html('用数据为空！').show()
                    }else if (data.code === 4){
                            // 跳转页面
                            location.href = data.next_url
                    }else if (data.code === 5){
                            $('#password').next().html('用户或者密码错误!').show()
                    }
                });
            });
    </script>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
<title>尚硅谷书城注册页面</title>
{% endblock title %}
{% block content %}
<body>
    {% block head %}
    {% endblock head %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>
		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="username" placeholder="请输入用户名">
                        <span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="password" id="password" placeholder="请输入密码">
                        <span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd" placeholder="请再次输入密码">
                        <span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email" placeholder="请输入邮箱">
                        <span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意"尚硅谷书城用户使用协议"</label>
                        <span class="error_tip">提示信息</span>
					</li>
					<li class="reg_sub">
                        <input id="btn" type="submit" value="注 册" name="">
					</li>
				</ul>
			</div>
		</div>
	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
    <script>
          $('#btn').click(function () {

              var name = $('#username').val();
              var password = $('#password').val();
              var cwpd = $('#cpwd').val();
              var email = $('#email').val();

              var params = {
                  'name': name,
                  'password': password,
                  'cwpd': cwpd,
                  'email': email
              };

              $.post('{% url "users:register_handle" %}', params , function(data){
                    if (data.code === 0){
                      $('#username').next().html('用户名已存在,请重新输入').show()
                  }else if(data.code === 1){
                      $('#username').next().html('用户名可以使用').show()
                  } else if(data.code === 2){
                      $('#cpwd').next().html('两次输入的密码不一致,请重新输入').show()
                  }else if (data.code === 3){
                      $('#cpwd').next().html('两次输入的密码一致,').show()
                  } else if (data.code === 4){
                            $('#email').next().html('邮箱格式不正确,请重新输入')
                        }
              });
          });

    </script>
    {% endblock content %}